### ISSUE TITLE
There are typos and grammar errors on README.md 

### ISSUE THREAD

**Issue by di-press** [courselab/snaskii21#18] opened 2021-11-10 19:25 UTC
Some grammar and typos corrections were made.

**Comment by aocard** [comment] 2021-11-15 16:10
I've made basic typo fixes on README.md. Leaving issue #19 open, for possible changes in clarity.

**Comment by Float07** [comment] 2021-11-16 01:26
@aocard the issue is still unsolved in `develop`, the changes are still pending in PR #19.
I'll reopen this issue.

**Comment by aocard** [comment] 2021-11-16 03:27
I've created a PR (#60) to address this now.
Question, should I close the issue when the PR is made or after it gets approved?

**Comment by Float07** [comment] 2021-11-16 10:40
>I've created a PR (#60) to address this now.

That's good but the problem is PR #19  was already taking care of this issue. Having two PR taking care of the same issue can lead to conflict and can waste someone's work. When you want to contribute to some issue that already has a PR then you can suggest changes to the PR made. I know PR #19 is pending for some time so maybe it's actually a good idea that you created a new PR to solve the issue.

You can take a look in the "Assignees" field on top of the page to check if someone is already taking care of it, and you can assign yourself to it if you want to do the tasks. The main point in it is making sure some work isn't made twice and no effort is wasted.
![image](https://user-images.githubusercontent.com/39651883/141970069-812890a1-6eba-42ce-be6b-b61aaba26ec8.png)


> Question, should I close the issue when the PR is made or after it gets approved?

After it gets approved and merged. But if you use something like "fixes #18" in the description, then the issue will be automatically solved after the merge is done, as you can see [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Sorry for the big text wall 😆

**Comment by Float07** [comment] 2022-01-03 18:08
PR #19 was closed without merge. I'll be closing this Issue.

**Closed as completed by Float07** 2022-01-03 18:08 UTC
Labels: doc, easy
